name: Publish Docker Github Package

on:
  release:
    types: [published]

jobs:
  push_to_registries:
    name: Push Docker image to GHCR and scan with Trivy
    runs-on: [self-hosted, macOS]
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Install Trivy on macOS
        run: |
          brew install aquasecurity/trivy/trivy

      - name: Scan Docker image with Trivy
        run: |
          trivy image --severity CRITICAL,HIGH --format table --exit-code 0 ghcr.io/${{ github.repository }}:$(echo "${{ steps.meta.outputs.tags }}" | cut -d ':' -f2)
